### ISSUE TITLE
画面クリアの代わりに

### ISSUE THREAD

**Issue by toma09to** [gamasang/Pachinko#1]
画面クリアすると、前の履歴が遥か彼方に飛んでいって困るので、カーソルを左上に移動させた上で右下まで全部消す操作をした方が良さそう

```diff
- printf("\033[2J");
+ printf("\033[1;1H\033[0J");
```

**Comment by toma09to** [comment]
実行前に表示されてた文字列消えちゃうけど致し方なしかな？

**Comment by gamasang** [comment]
例えば何が消えてる？2024/08/03 1:27、toma09to ***@***.***>のメール:﻿
実行前に表示されてた文字列消えちゃうけど致し方なしかな？
